[tool.mypy]
mypy_path = './src/'
show_error_codes = true
strict = true
pretty = true
ignore_missing_imports = false
warn_unused_configs = true
disallow_subclassing_any = false
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
follow_imports_for_stubs = true
namespace_packages = true
show_absolute_path = true

[tool.black]
target-version = ["py311"]
verbose = true
preview = true
line-length = 100
include_trailing_comma = true
include = '\.pyi?$'
exclude = '''
(
    \.eggs
  | \.git
  | build
  | dist
  | venv
  | docs
)
'''

[tool.ruff]
target-version = "py311"
ignore-init-module-imports = true
select = [
  "E",     # pycodestyle
  "W",     # pycodestyle
  "F",     # pyflakes
  "UP",    # pyupgrade
  "I",     # isort
  "ASYNC", # flake8-async
  "FIX",   # flake8-fixme
  "PTH",   # flake8-use-pathlib
  "ERA",   # eradicate
  "RUF",   # Ruff-specific rules
  "C90",   # McCabe complexity
]
ignore = [
    "E501",   # handled by black
    # backward compatibility
    "UP006",
    "UP007",
    "UP035",
]
fixable = ["ALL"]

[tool.ruff.isort]
lines-after-imports = 2
known-local-folder = ["app", "auth"]

[tool.ruff.pyupgrade]
keep-runtime-typing = true

[tool.ruff.pycodestyle]
max-doc-length = 72
