"""Initial

Revision ID: 1afdf087c3fe
Revises:
Create Date: 2023-12-15 16:42:11.548503

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


import src.infrastructure.db.types as types


# revision identifiers, used by Alembic.
revision: str = "1afdf087c3fe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", types.IDType(), nullable=False),
        sa.Column("first_name", types.FirstNameType(), nullable=False),
        sa.Column("last_name", types.LastNameType(), nullable=False),
        sa.Column("username", types.UsernameType(), nullable=False),
        sa.Column("email", types.EmailType(), nullable=False),
        sa.Column("hashed_password", types.HashedPasswordType(), nullable=False),
        sa.Column("role", types.RoleType("ADMIN", "USER"), nullable=False),
        sa.Column("created_at", types.CreatedAtType(timezone=True), nullable=False),
        sa.Column("updated_at", types.UpdatedAtType(timezone=True), nullable=False),
        sa.Column("deleted_at", types.DeletedAtType(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
