"""Initial

Revision ID: 9573dc168541
Revises: 1afdf087c3fe
Create Date: 2023-12-15 16:55:11.041201

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import src.infrastructure.db.types as types


# revision identifiers, used by Alembic.
revision: str = "9573dc168541"
down_revision: Union[str, None] = "1afdf087c3fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", types.HashedPasswordType(), nullable=True))
    op.alter_column("user", "first_name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "last_name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "username", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("user", "email", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "user",
        "role",
        existing_type=postgresql.ENUM("ADMIN", "USER", name="role_enum"),
        nullable=True,
    )
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("hashed_password", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.alter_column(
        "user",
        "role",
        existing_type=postgresql.ENUM("ADMIN", "USER", name="role_enum"),
        nullable=False,
    )
    op.alter_column("user", "email", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "username", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "last_name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("user", "first_name", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("user", "password")
    # ### end Alembic commands ###
